apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: testdatabase
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: 
    - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            - name: secret-pass
              key: password
  PGDATA: /var/lib/postgresql/data/pgdata